name: build

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache APT packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq help2man libgmp-dev libmpfr-dev libboost-all-dev cmake build-essential libboost-program-options-dev libreadline-dev libgmp-dev python3-venv

    - name: Install ccache
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache

    - name: Configure ccache
      run: |
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        ccache --max-size=2G
        ccache --show-stats

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Cache Python virtual environment
      uses: actions/cache@v3
      with:
        path: manthan-venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt', '**/configure_dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install Python dependencies
      run: |
        if [ ! -d "manthan-venv" ]; then
          python3 -m venv manthan-venv
          source manthan-venv/bin/activate
          python3 -m pip install -r requirements.txt
        else
          source manthan-venv/bin/activate
        fi
        ./configure_dependencies.sh --all
        python3 -m pip install -r requirements.txt
        ./configure_dependencies.sh --all
        ./manthan.py benchmarks/factorization8.qdimacs
